all: fileopen fileread filewrite

fileopen:
	gcc -Wall -o fileopen fileopen.c

fileread:
	gcc -Wall -o fileread fileread.c

filewrite:
	gcc -Wall -o filewrite filewrite.c

marksfile:
	gcc -Wall -g -O0 -o marks marks.c

clean:
	-rm fileopen fileread filewrite marks